// ─── Core Player ─────────────────────────────────────────────────────────────

export interface PlayerSkills {
  negotiation: number;
  networking: number;
  focus: number;
  discipline: number;
  leadership: number;
  reputation: number;
}

export interface Player extends PlayerSkills {
  id: string;
  name: string;
  level: number;
  total_xp: number;
  current_xp: number;
  xp_to_next_level: number;
  no_trading_streak: number;
  skill_points: number;
  total_skill_points_earned: number;
  money: number;
  monthly_income: number;
  empire_value: number;
  // ── Vitality stats ──────────────────────────────────────
  energy: number;       // 0–max_energy: consumed by calls/meetings, restored by rest
  max_energy: number;   // capacity; grows with discipline
  stress: number;       // 0–100: raised by trading/failures, reduced by rest
  morale: number;       // 0–100: boosted by deals/routines, hit by failures
}

export interface PlayerStats {
  deals_closed: number;
  properties_acquired: number;
  total_investment: number;
  contracts_violated: number;
  trades_executed: number;
  quest_completed: number;
}

// ─── Level Rewards ────────────────────────────────────────────────────────────

export interface LevelReward {
  level: number;
  title: string;
  flavour_text: string;
  skill_points_granted: number;
  auto_negotiation: number;
  auto_networking: number;
  auto_focus: number;
  auto_discipline: number;
  auto_leadership: number;
  auto_reputation: number;
  unlock_type: string | null;
  unlock_ref: string | null;
  badge_color: string;
}

// Emitted when a level-up is processed
export interface LevelUpEvent {
  newLevel: number;
  reward: LevelReward;
  statGains: Partial<PlayerSkills>;
  skillPointsGained: number;
}

// ─── Districts ───────────────────────────────────────────────────────────────

export interface District {
  id: string;
  name: string;
  description: string;
  region: string;
  base_difficulty: number;
  hotel_opportunity_count: number;
  xp_bonus: number;
  unlock_requirement: number;
  max_territory_level: number;
}

export interface PlayerDistrict {
  id: string;
  district_id: string;
  control_level: number;
  hotels_invested: number;
  market_share: number;
  territory_level: number;
  district_reputation: number;
  is_unlocked: boolean;
  opportunities_unlocked: number;
  dominance_xp: number;
  last_quest_completed_at: string | null;
}

// ─── AI Suggestions (optional opportunities generated by the system) ─────────

export type SuggestionStatus = 'pending' | 'accepted' | 'dismissed' | 'expired' | 'snoozed';
export type SuggestionType   = 'strategic' | 'tactical' | 'opportunity' | 'risk_mitigation';
export type SuggestionPriority = 'high' | 'medium' | 'low';

export interface AISuggestion {
  id: string;
  player_id: string;
  title: string;
  description: string;
  rationale: string;
  category: string;
  suggestion_type: SuggestionType;
  priority: SuggestionPriority;
  estimated_xp: number;
  estimated_money: number;
  difficulty: number;
  tags: string[];
  source: string;
  status: SuggestionStatus;
  accepted_quest_id: string | null;
  snoozed_until: string | null;
  expires_at: string;
  created_at: string;
  updated_at: string;
}

// ─── Official Quests (real business tasks synced from Notion) ────────────────

export interface OfficialQuest {
  id: string;
  notion_id: string;
  title: string;
  status: string | null;
  xp: number;
  priority: string | null;
  difficulty: string | null;
  impact: string | null;
  quest_type: string | null;
  completed: boolean;
  recurring: boolean;
  level_requirement: number;
  reward: string | null;
  deadline: string | null;
  updated_at: string;
}

// ─── Quests ──────────────────────────────────────────────────────────────────

export interface Quest {
  id: string;
  title: string;
  description: string;
  quest_type: 'daily' | 'weekly' | 'main' | 'legendary';
  category: string;
  xp_reward: number;
  difficulty: number;
}

export interface PlayerQuest {
  id: string;
  quest_id: string;
  status: 'active' | 'completed' | 'abandoned';
  progress: number;
  xp_earned: number;
  quest?: Quest;
}

// ─── Achievements ─────────────────────────────────────────────────────────────

export interface Achievement {
  id: string;
  name: string;
  description: string;
  icon: string;
  xp_reward: number;
}

// ─── Quest Completion Event (for toast animations) ────────────────────────────

export interface QuestCompletionEvent {
  questId: string;
  title: string;
  xpEarned: number;
  moneyEarned: number;
  reputationEarned: number;
  skillPointsEarned: number;
  bonusType: string | null;
  bonusValue: number;
  difficulty: number;
  questType: 'daily' | 'weekly' | 'main' | 'legendary';
}

// ─── Office Upgrades ──────────────────────────────────────────────────────────

export interface OfficeUpgrade {
  id: string;           // uuid
  slug: string;
  name: string;
  description: string;
  tier: number;
  cost: number;
  reputation_bonus: number;
  income_multiplier_bonus: number;
  xp_bonus_pct: number;
  monthly_revenue_bonus: number;
  required_level: number;
  required_slug: string | null;
  icon: string;
}

// ─── District Market System ───────────────────────────────────────────────────

export type TrendDirection = 'rising' | 'falling' | 'stable' | 'volatile';
export type EventSeverity  = 'info' | 'opportunity' | 'warning' | 'alert';

export interface DistrictMarketData {
  id: string;
  district_id: string;
  market_temp: number;        // 0-100: overall temperature
  opportunities: number;      // 0-100: active deal flow
  competition: number;        // 0-100: how contested
  investor_activity: number;  // 0-100: capital circulating
  tourism_growth: number;     // 0-100: visitor growth
  luxury_demand: number;      // 0-100: high-end market
  trend_direction: TrendDirection;
  last_evolved_at: string;
}

export interface DistrictEvent {
  id: string;
  district_id: string;
  event_type: string;
  severity: EventSeverity;
  title: string;
  description: string;
  impact: Record<string, number>;
  expires_at: string | null;
  created_at: string;
}

// ─── Reputation System ────────────────────────────────────────────────────────

export type RepTrack = 'investor' | 'owner' | 'market' | 'operator' | 'broker' | 'luxury';

export interface PlayerReputation {
  id: string;
  player_id: string;
  investor_rep: number;
  owner_rep: number;
  market_rep: number;
  operator_rep: number;
  broker_rep: number;
  luxury_rep: number;
  investor_rep_total: number;
  owner_rep_total: number;
  market_rep_total: number;
  operator_rep_total: number;
  broker_rep_total: number;
  luxury_rep_total: number;
}

export interface RepRank {
  rank: number;           // 1-7
  label: string;
  badge: string;
  minScore: number;
  color: string;
  glowColor: string;
  description: string;
}

export const REP_RANKS: RepRank[] = [
  { rank: 1, label: 'Unknown',       badge: 'UNK',  minScore: 0,   color: '#475569', glowColor: 'rgba(71,85,105,0.3)',   description: 'No standing in this area yet.' },
  { rank: 2, label: 'Emerging',      badge: 'EMR',  minScore: 25,  color: '#3b82f6', glowColor: 'rgba(59,130,246,0.3)',  description: 'Beginning to build a name.' },
  { rank: 3, label: 'Established',   badge: 'EST',  minScore: 75,  color: '#06b6d4', glowColor: 'rgba(6,182,212,0.3)',   description: 'A recognized presence in the market.' },
  { rank: 4, label: 'Respected',     badge: 'RSP',  minScore: 150, color: '#10b981', glowColor: 'rgba(16,185,129,0.3)',  description: 'Sought out for deals and partnerships.' },
  { rank: 5, label: 'Distinguished', badge: 'DST',  minScore: 275, color: '#f59e0b', glowColor: 'rgba(245,158,11,0.3)',  description: 'One of the most trusted names in Portugal.' },
  { rank: 6, label: 'Elite',         badge: 'ELT',  minScore: 450, color: '#f97316', glowColor: 'rgba(249,115,22,0.3)',  description: 'Top tier. Only the best reach you.' },
  { rank: 7, label: 'Legendary',     badge: 'LEG',  minScore: 700, color: '#ef4444', glowColor: 'rgba(239,68,68,0.35)',  description: 'A legend. Your name opens every door.' },
];

export const getRepRank = (score: number): RepRank =>
  [...REP_RANKS].reverse().find(r => score >= r.minScore) ?? REP_RANKS[0];

export const getNextRepRank = (score: number): RepRank | null => {
  const idx = REP_RANKS.findIndex(r => score < r.minScore);
  return idx === -1 ? null : REP_RANKS[idx];
};

export type RepUnlockCategory =
  | 'private_opportunity'   // hidden one-time investment chance
  | 'legendary_investor'    // access to a legendary investor NPC
  | 'off_market_portfolio'  // multi-property off-market bundle
  | 'hidden_district'       // unlocks a secret/hidden district
  | 'deal'
  | 'investor'
  | 'listing'
  | 'mission';

export interface RepUnlock {
  track: RepTrack;
  minScore: number;
  label: string;
  description: string;
  unlockType: RepUnlockCategory;
  icon: string;
  // Preview card shown when the unlock is reached
  previewTitle?: string;
  previewBody?: string;
  previewValue?: string;      // e.g. "€4.2M deal" or "Hidden District"
  previewTier?: 'rare' | 'epic' | 'legendary';
}

export const REP_UNLOCKS: RepUnlock[] = [
  // ── Investor track ────────────────────────────────────────────────────────
  {
    track: 'investor', minScore: 25, unlockType: 'investor',
    label: 'Angel Network Access', icon: 'user-plus',
    description: 'Connect with individual angel investors for seed-stage hospitality projects.',
  },
  {
    track: 'investor', minScore: 75, unlockType: 'private_opportunity',
    label: 'Private Seed Round', icon: 'lock-open',
    description: 'A boutique Lisbon hotel operator invites you into a €600k private seed round — not listed anywhere.',
    previewTitle: 'Private Seed Round — Lisbon Boutique', previewBody: 'Exclusive co-investment opportunity from a growing operator network. No broker. No competition.',
    previewValue: '€600k · Seed', previewTier: 'rare',
  },
  {
    track: 'investor', minScore: 150, unlockType: 'legendary_investor',
    label: 'Legendary Investor: Carlos Mendes', icon: 'users',
    description: 'Carlos Mendes, founder of Atlântico Capital, opens a direct line. His mandates exceed €50M.',
    previewTitle: 'Carlos Mendes — Atlântico Capital', previewBody: 'Billionaire investor with 30 years in Portuguese hospitality. His backing turns boutiques into brands.',
    previewValue: '€50M+ mandate', previewTier: 'epic',
  },
  {
    track: 'investor', minScore: 275, unlockType: 'off_market_portfolio',
    label: 'Sovereign Off-Market Bundle', icon: 'landmark',
    description: 'A SWF quietly liquidates three Algarve resorts. You are the first call. Total portfolio: €28M.',
    previewTitle: 'Algarve Resort Portfolio — Off-Market', previewBody: 'Three 4-star properties across the Algarve coast. Sovereign seller requires absolute discretion.',
    previewValue: '€28M · 3 properties', previewTier: 'epic',
  },
  {
    track: 'investor', minScore: 450, unlockType: 'hidden_district',
    label: 'Hidden District: Setúbal Peninsula', icon: 'globe',
    description: 'An undiscovered investment corridor south of Lisbon surfaces through your institutional network.',
    previewTitle: 'Setúbal Peninsula', previewBody: 'Untapped coastal corridor with zero institutional coverage. First-mover advantage is yours.',
    previewValue: 'Hidden District', previewTier: 'legendary',
  },
  {
    track: 'investor', minScore: 700, unlockType: 'legendary_investor',
    label: 'Global LP Syndicate', icon: 'building',
    description: 'A global LP syndicate invites you to co-manage a €120M cross-border hospitality fund.',
    previewTitle: 'LP Syndicate — Cross-Border Fund', previewBody: 'Rare invitation to manage institutional capital across Portugal, Spain, and Morocco.',
    previewValue: '€120M fund', previewTier: 'legendary',
  },

  // ── Owner track ───────────────────────────────────────────────────────────
  {
    track: 'owner', minScore: 25, unlockType: 'listing',
    label: 'Local Owner Introductions', icon: 'door-open',
    description: 'Small local hotel owners start taking your calls and sharing early intel.',
  },
  {
    track: 'owner', minScore: 75, unlockType: 'off_market_portfolio',
    label: 'Off-Market: Porto Heritage Hotel', icon: 'lock-open',
    description: 'A family-owned 19th-century building in central Porto is being quietly sold. No agent. Direct approach only.',
    previewTitle: 'Porto Heritage Hotel — Off-Market', previewBody: 'Third-generation family reluctantly selling. The building has never been publicly listed in 40 years.',
    previewValue: '€3.1M · Historic', previewTier: 'rare',
  },
  {
    track: 'owner', minScore: 150, unlockType: 'deal',
    label: 'Exclusive Portfolio Mandate', icon: 'briefcase',
    description: 'A portfolio owner hands you exclusive representation of five properties across the North.',
    previewTitle: 'Northern Portfolio Mandate', previewBody: '5 hotels, €18M total. Seller gives you 90-day exclusivity. No competition.',
    previewValue: '€18M · 5 properties', previewTier: 'epic',
  },
  {
    track: 'owner', minScore: 275, unlockType: 'private_opportunity',
    label: 'Distressed Asset Network', icon: 'star',
    description: 'Owner networks route you distressed assets before they reach the open market.',
    previewTitle: 'Distressed Coastal Resort', previewBody: 'Receiver-managed resort facing forced sale. Price 35% below market. Institutional interest imminent.',
    previewValue: '€7.8M · Distressed', previewTier: 'epic',
  },
  {
    track: 'owner', minScore: 450, unlockType: 'hidden_district',
    label: 'Hidden District: Serra da Estrela', icon: 'crown',
    description: 'Mountain owners reveal an emerging wellness tourism corridor invisible to city-based advisors.',
    previewTitle: 'Serra da Estrela', previewBody: 'Mountain resort corridor gaining traction with European wellness tourists. Zero competition yet.',
    previewValue: 'Hidden District', previewTier: 'legendary',
  },

  // ── Market track ──────────────────────────────────────────────────────────
  {
    track: 'market', minScore: 25, unlockType: 'deal',
    label: 'Media Coverage', icon: 'newspaper',
    description: 'Industry press begins covering your deals, generating inbound deal flow.',
  },
  {
    track: 'market', minScore: 75, unlockType: 'mission',
    label: 'Speaking Invitations', icon: 'mic',
    description: 'Invited to speak at regional hotel conferences. New contacts on every stage.',
  },
  {
    track: 'market', minScore: 150, unlockType: 'private_opportunity',
    label: 'Conference Off-Market Deal', icon: 'award',
    description: 'A speaker in the row behind you slides you a napkin. His €5M Porto hotel is not for sale. Except to you.',
    previewTitle: 'Napkin Deal — Porto', previewBody: 'Whispered offer at the Hospitality Summit. €5M penthouse-hotel hybrid. Not listed. Never will be.',
    previewValue: '€5M · Whispered', previewTier: 'epic',
  },
  {
    track: 'market', minScore: 275, unlockType: 'mission',
    label: 'Legendary Quest Unlock', icon: 'scroll',
    description: 'Your market authority unlocks the legendary advisory quest chain.',
  },
  {
    track: 'market', minScore: 450, unlockType: 'hidden_district',
    label: 'Hidden District: Azores Private Island', icon: 'trophy',
    description: 'Your market profile attracts a private developer offering exclusive Azores island advisory.',
    previewTitle: 'Azores Private Island Circuit', previewBody: 'Three island micro-resorts. Off-grid luxury. Zero institutional coverage. Media connections opened this door.',
    previewValue: 'Hidden District', previewTier: 'legendary',
  },

  // ── Operator track ────────────────────────────────────────────────────────
  {
    track: 'operator', minScore: 25, unlockType: 'deal',
    label: 'Operator Introductions', icon: 'hotel',
    description: 'Local hotel operators trust your due diligence assessments.',
  },
  {
    track: 'operator', minScore: 75, unlockType: 'deal',
    label: 'Bigger Deal Access', icon: 'trending-up',
    description: 'Operating companies include you in larger, more complex transactions.',
  },
  {
    track: 'operator', minScore: 150, unlockType: 'off_market_portfolio',
    label: 'Pre-Opening Mandate', icon: 'handshake',
    description: 'An international brand hands you a confidential pre-opening mandate — before the building is announced.',
    previewTitle: 'Pre-Opening Hotel — Confidential', previewBody: 'A five-star brand opening in Chiado needs an exclusive advisor before the press release goes out.',
    previewValue: '€12M · Pre-opening', previewTier: 'epic',
  },
  {
    track: 'operator', minScore: 275, unlockType: 'deal',
    label: 'Exclusive Operator Deals', icon: 'gem',
    description: 'Top-tier operators create bespoke deal structures exclusively for you.',
  },
  {
    track: 'operator', minScore: 450, unlockType: 'hidden_district',
    label: 'Hidden District: Comporta Reserve', icon: 'key',
    description: 'Operator networks surface the Comporta luxury reserve — a zero-competition ultra-premium zone.',
    previewTitle: 'Comporta Reserve', previewBody: 'Portugal\'s most exclusive coastal enclave. No public listings. Operator introductions are the only entry.',
    previewValue: 'Hidden District', previewTier: 'legendary',
  },

  // ── Broker track ──────────────────────────────────────────────────────────
  {
    track: 'broker', minScore: 25, unlockType: 'deal',
    label: 'Broker Co-Mandates', icon: 'handshake',
    description: 'Local brokers begin sharing co-mandate opportunities and referral deal flow.',
  },
  {
    track: 'broker', minScore: 75, unlockType: 'private_opportunity',
    label: 'Broker Dark Pool', icon: 'lock-open',
    description: 'Entry into the informal broker dark pool — deals shared only between trusted advisors before any listing.',
    previewTitle: 'Dark Pool: Lisbon Riverside', previewBody: 'A converted warehouse hotel. Owner is a broker contact. Asking price €4.5M, real value estimated €6.2M.',
    previewValue: '€4.5M · Dark pool', previewTier: 'rare',
  },
  {
    track: 'broker', minScore: 150, unlockType: 'off_market_portfolio',
    label: 'Cross-Border Referral Network', icon: 'globe',
    description: 'Brokers in Madrid, London and Paris route Portuguese deal flow exclusively through you.',
    previewTitle: 'Cross-Border Referral Bundle', previewBody: 'Three assets referred from London brokers. Sellers want Portuguese expertise. You are the only local contact.',
    previewValue: '€22M · 3 assets', previewTier: 'epic',
  },
  {
    track: 'broker', minScore: 275, unlockType: 'legendary_investor',
    label: 'Legendary Broker: Isabel Ferreira', icon: 'star',
    description: 'Isabel Ferreira — Iberia\'s top hospitality broker with 25 years of off-market deal flow — partners with you.',
    previewTitle: 'Isabel Ferreira — Partner', previewBody: 'Access to her proprietary off-market database and warm introductions to every major seller in Portugal.',
    previewValue: '500+ off-market listings', previewTier: 'epic',
  },
  {
    track: 'broker', minScore: 450, unlockType: 'hidden_district',
    label: 'Hidden District: Douro Valley Private', icon: 'gem',
    description: 'Broker network surfaces a quiet premium corridor along the Douro wine valley — invisible to outsiders.',
    previewTitle: 'Douro Valley Private Circuit', previewBody: 'Wine estates converting to boutique hotels. Owners only deal through trusted broker referrals.',
    previewValue: 'Hidden District', previewTier: 'legendary',
  },

  // ── Luxury track ──────────────────────────────────────────────────────────
  {
    track: 'luxury', minScore: 25, unlockType: 'deal',
    label: 'Luxury Tier Entry', icon: 'gem',
    description: 'Four and five-star properties begin appearing in your deal flow. Premium clients take notice.',
  },
  {
    track: 'luxury', minScore: 75, unlockType: 'private_opportunity',
    label: 'Ultra-HNW Private Placement', icon: 'crown',
    description: 'An UHNW family office invites you to advise on a silent €8M acquisition — no agent, no timeline.',
    previewTitle: 'UHNW Private Placement', previewBody: 'A €8M Alentejo wine estate with a boutique hotel. Family office buyer. Absolute confidentiality required.',
    previewValue: '€8M · Ultra-private', previewTier: 'rare',
  },
  {
    track: 'luxury', minScore: 150, unlockType: 'off_market_portfolio',
    label: 'Five-Star Portfolio Access', icon: 'star',
    description: 'A five-star hotel group quietly rotates assets. Three properties in Lisbon, Porto, and Cascais.',
    previewTitle: '5-Star Portfolio Rotation', previewBody: 'Group restructuring after succession. Three flagship hotels. Combined €85M. Never to be publicly listed.',
    previewValue: '€85M · 3 flagships', previewTier: 'epic',
  },
  {
    track: 'luxury', minScore: 275, unlockType: 'legendary_investor',
    label: 'Legendary Investor: Duchess of Cascais', icon: 'landmark',
    description: 'The Duchess of Cascais — reclusive heir to a hospitality dynasty — grants you exclusive access to her portfolio.',
    previewTitle: 'Duchess of Cascais', previewBody: 'Inherited portfolio of 9 historic properties. Has never worked with an external advisor. Until now.',
    previewValue: '9 properties · Dynasty', previewTier: 'epic',
  },
  {
    track: 'luxury', minScore: 450, unlockType: 'hidden_district',
    label: 'Hidden District: Sintra Palaces', icon: 'crown',
    description: 'The ultra-premium Sintra palace circuit surfaces — properties that exist in no registry, sold only by word of mouth.',
    previewTitle: 'Sintra Palace Circuit', previewBody: 'Seven palace conversions across Sintra. Not in any database. Owners only trust luxury-tier advisors with proven discretion.',
    previewValue: 'Hidden District', previewTier: 'legendary',
  },
  {
    track: 'luxury', minScore: 700, unlockType: 'legendary_investor',
    label: 'Global Luxury Fund Access', icon: 'globe',
    description: 'The Monaco-based Prestige Hospitality Fund — €500M AUM — invites you to co-manage their Iberian portfolio.',
    previewTitle: 'Prestige Hospitality Fund', previewBody: 'Monaco-based. €500M AUM. They invest only through advisors with proven luxury credentials. You qualify.',
    previewValue: '€500M AUM', previewTier: 'legendary',
  },
];

export const REP_TRACK_META: Record<RepTrack, { label: string; color: string; icon: string; description: string }> = {
  investor: { label: 'Investor Rep',  color: '#3b82f6', icon: 'bar-chart-2',  description: 'Standing with capital providers, family offices, and institutional investors.' },
  owner:    { label: 'Owner Rep',     color: '#10b981', icon: 'home',         description: 'Trust from property owners and sellers who share off-market opportunities with you.' },
  market:   { label: 'Market Rep',    color: '#f59e0b', icon: 'trending-up',  description: 'Brand recognition and authority in the broader Portuguese hotel investment market.' },
  operator: { label: 'Operator Rep',  color: '#f97316', icon: 'settings',     description: 'Relationships with hotel operators and international management companies.' },
  broker:   { label: 'Broker Rep',    color: '#06b6d4', icon: 'briefcase',    description: 'Trust within the broker community — dark pool access and cross-border referral networks.' },
  luxury:   { label: 'Luxury Rep',    color: '#a78bfa', icon: 'gem',          description: 'Standing in the ultra-premium and UHNW segment — palaces, dynasties, and five-star portfolios.' },
};

// ─── Story Events ─────────────────────────────────────────────────────────────

export type StoryChoiceEffect = {
  money?: number;               // positive = gain, negative = cost
  xp?: number;
  reputation?: number;          // player.reputation stat
  market_share_delta?: number;  // applied to a district (0.0–1.0 range)
  rep_delta?: Partial<Record<RepTrack, number>>;
  district_id?: string | null;  // which district is affected
  // narrative tag for future unlock logic
  tag?: string;
};

export interface StoryChoice {
  id: string;         // e.g. 'accept' | 'decline' | 'negotiate'
  label: string;      // short CTA label
  description: string;// one-line consequence hint
  effects: StoryChoiceEffect;
  // Optional min requirements to show this choice
  requiresLevel?: number;
  requiresRepTrack?: { track: RepTrack; minScore: number };
}

export type StoryCategory =
  | 'investor'      // capital / fund events
  | 'owner'         // hotel owner events
  | 'market'        // macro / sector events
  | 'competitor'    // rival advisory firms
  | 'opportunity';  // off-market / rare finds

export interface StoryEventTemplate {
  id: string;
  category: StoryCategory;
  title: string;
  body: string;                 // 2-3 sentence narrative
  accentColor: string;
  icon: string;                 // lucide icon name (string for lookup)
  choices: StoryChoice[];
  // Spawn conditions (all optional — missing = always eligible)
  minLevel?: number;
  requiresActiveDistrict?: boolean;
  cooldownHours?: number;       // min hours between same template firing
}

export interface ActiveStoryEvent {
  id: string;                   // unique instance id
  templateId: string;
  category: StoryCategory;
  title: string;
  body: string;
  accentColor: string;
  icon: string;
  choices: StoryChoice[];
  districtId?: string;          // contextual district (if any)
  districtName?: string;
  spawnedAt: number;            // Date.now()
}

// ─── Rare Opportunities ───────────────────────────────────────────────────────

export type RareTier = 'rare' | 'epic' | 'legendary';

export interface RareOpportunityReward {
  money: number;
  xp: number;
  rep_delta: Partial<Record<RepTrack, number>>;
  market_share_delta?: number;  // applied to player's strongest district
  reputation?: number;          // player stat
}

export interface RareOpportunityTemplate {
  id: string;
  tier: RareTier;
  title: string;
  subtitle: string;      // e.g. "Off-Market · Lisbon · €4.2M"
  body: string;
  reward: RareOpportunityReward;
  declineReward?: RareOpportunityReward;  // small consolation for declining
  timerSeconds: number;                   // countdown duration
  requiresLevel: number;
  requiresRepTrack?: { track: RepTrack; minScore: number };
  accentColor: string;
  glowColor: string;
  icon: string;           // lucide icon name
  cooldownHours: number;
  acceptLabel: string;
  declineLabel: string;
}

export interface ActiveRareOpportunity {
  id: string;
  templateId: string;
  tier: RareTier;
  title: string;
  subtitle: string;
  body: string;
  reward: RareOpportunityReward;
  declineReward?: RareOpportunityReward;
  timerSeconds: number;
  requiresLevel: number;
  requiresRepTrack?: { track: RepTrack; minScore: number };
  accentColor: string;
  glowColor: string;
  icon: string;
  acceptLabel: string;
  declineLabel: string;
  spawnedAt: number;   // Date.now()
  districtId?: string;
  districtName?: string;
}

// ─── Deal Completion Event ────────────────────────────────────────────────────

export interface DealCompletionEvent {
  districtName: string;
  dealName: string;
  moneyEarned: number;
  reputationEarned: number;
  dominanceGained: number;
  accentColor: string;
}

// ─── Cinematic Deal ───────────────────────────────────────────────────────────
// Imported from DealCinematicSequence to avoid circular deps — re-exported here for GameState

export type DealTier = 'standard' | 'major' | 'legendary';

export interface CinematicNegotiationRound {
  playerMove: string;
  opponentResponse: string;
  advantage: 'player' | 'opponent' | 'neutral';
  outcomeText: string;
}

export interface PendingCinematicDeal {
  id: string;
  tier: DealTier;
  dealName: string;
  districtName: string;
  accentColor: string;
  moneyEarned: number;
  reputationEarned: number;
  dominanceGained: number;
  xpEarned: number;
  opponentName: string;
  opponentTitle: string;
  dealValue: number;
  negotiationRounds: CinematicNegotiationRound[];
}

// ─── NPC System ──────────────────────────────────────────────────────────────

export type NPCType = 'investor' | 'owner' | 'broker' | 'developer' | 'operator' | 'competitor';
export type NPCPersonality = 'analytical' | 'aggressive' | 'charming' | 'cautious' | 'visionary' | 'pragmatic';
export type NPCNegotiationStyle = 'hardball' | 'collaborative' | 'emotional' | 'data_driven' | 'intuitive';
export type RelationshipStatus = 'stranger' | 'acquaintance' | 'contact' | 'ally' | 'partner' | 'rival';

export interface NPC {
  id: string;
  slug: string;
  type: NPCType;
  name: string;
  title: string;
  district_name: string;
  personality: NPCPersonality;
  negotiation_style: NPCNegotiationStyle;
  avatar_initials: string;
  accent_color: string;
  base_trust: number;
  min_player_level: number;
  rep_track: RepTrack;
  backstory: string;
}

export interface PlayerNPCRelationship {
  id: string;
  player_id: string;
  npc_id: string;
  trust_level: number;
  relationship_status: RelationshipStatus;
  interaction_count: number;
  last_interaction_at: string | null;
  notes: string[];
  unlocked_at: string;
}

export interface NPCDialogueChoice {
  id: string;
  label: string;
  subtext: string;           // consequence hint
  trust_delta: number;
  rep_delta: number;
  money_delta: number;
  outcome_text: string;      // what the NPC says after this choice
  note?: string;             // memory note saved to relationship
  requiresNegotiation?: number;  // min negotiation skill
  requiresNetworking?: number;
  requiresTrust?: number;
}

export interface NPCDialogue {
  id: string;
  npc_slug: string;
  trigger: 'first_meet' | 'low_trust' | 'growing_trust' | 'ally' | 'partner' | 'rival' | 'generic';
  minTrust?: number;
  maxTrust?: number;
  greeting: string;          // NPC's opening line
  body: string;              // context/narrative paragraph
  choices: NPCDialogueChoice[];
}

export interface ActiveNPCDialogue {
  npc: NPC;
  relationship: PlayerNPCRelationship;
  dialogue: NPCDialogue;
  phase: 'intro' | 'choices' | 'outcome';
  selectedChoice: NPCDialogueChoice | null;
}

// ─── Rival System ────────────────────────────────────────────────────────────

export type RivalType = 'firm' | 'broker' | 'boutique' | 'international';
export type RivalEventType =
  | 'territory_encroach'
  | 'deal_stolen'
  | 'investor_poached'
  | 'rep_attack'
  | 'market_undercutting'
  | 'territory_takeover'
  | 'collaboration_offer';

export interface RivalFirm {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  type: RivalType;
  aggression: number;       // 1–10
  reputation_score: number; // 0–100
  market_focus: string;
  accent_color: string;
  founder_name: string;
  bio: string;
  specialisation: string;
  is_active: boolean;
}

export interface RivalDistrictPresence {
  id: string;
  rival_id: string;
  district_id: string;
  market_share: number;   // 0–1
  deal_count: number;
  last_active_at: string;
}

export interface RivalEvent {
  id: string;
  rival_id: string;
  player_id: string;
  event_type: RivalEventType;
  district_id: string | null;
  title: string;
  description: string;
  severity: EventSeverity;
  impact_market_share: number;
  impact_reputation: number;
  impact_money: number;
  is_read: boolean;
  created_at: string;
}

// ─── Game State ───────────────────────────────────────────────────────────────

export interface GameState {
  player: Player | null;
  stats: PlayerStats | null;
  districts: District[];
  playerDistricts: Map<string, PlayerDistrict>;
  officeUpgrades: OfficeUpgrade[];
  purchasedUpgradeSlugs: Set<string>;
  reputation: PlayerReputation | null;
  districtMarket: Map<string, DistrictMarketData>;
  districtEvents: Map<string, DistrictEvent[]>;
  quests: Quest[];
  playerQuests: PlayerQuest[];
  // Dynamic quest engine (AI/game-generated)
  dynamicQuests: import('../services/questEngine').DynamicQuest[];
  // Official quests (real business tasks from Notion)
  officialQuests: OfficialQuest[];
  // AI-generated optional mission suggestions
  aiSuggestions: AISuggestion[];
  achievements: Achievement[];
  unlockedAchievements: Set<string>;
  levelRewards: Map<number, LevelReward>;
  pendingLevelUps: LevelUpEvent[];
  pendingQuestCompletions: QuestCompletionEvent[];
  pendingDealCompletions: DealCompletionEvent[];
  pendingCinematicDeal: PendingCinematicDeal | null;
  npcs: NPC[];
  npcRelationships: Map<string, PlayerNPCRelationship>; // keyed by npc_id
  activeNPCDialogue: ActiveNPCDialogue | null;
  // Rival system
  rivals: RivalFirm[];
  rivalPresence: Map<string, RivalDistrictPresence[]>; // keyed by district_id
  rivalEvents: RivalEvent[];
  pendingRivalEvents: RivalEvent[];
  loading: boolean;
}

// ─── Skill unlock thresholds ─────────────────────────────────────────────────

export interface SkillUnlock {
  stat: keyof PlayerSkills;
  threshold: number;
  label: string;
  description: string;
  type: 'deal' | 'investor' | 'territory' | 'quest';
}

export const SKILL_UNLOCKS: SkillUnlock[] = [
  { stat: 'negotiation', threshold: 20, label: 'Mid-Market Deals',      description: 'Access deals above €500k',           type: 'deal' },
  { stat: 'negotiation', threshold: 40, label: 'Premium Deals',         description: 'Access deals above €2M',             type: 'deal' },
  { stat: 'negotiation', threshold: 70, label: 'Institutional Deals',   description: 'Access deals above €10M',            type: 'deal' },
  { stat: 'networking',  threshold: 20, label: 'Angel Investors',       description: 'Connect with angel investors',       type: 'investor' },
  { stat: 'networking',  threshold: 40, label: 'Family Offices',        description: 'Access family office capital',       type: 'investor' },
  { stat: 'networking',  threshold: 70, label: 'Institutional Funds',   description: 'Access PE and sovereign funds',      type: 'investor' },
  { stat: 'leadership',  threshold: 25, label: 'Team of 3',             description: 'Build a small advisory team',        type: 'investor' },
  { stat: 'leadership',  threshold: 50, label: 'Full Advisory Firm',    description: 'Scale to a full boutique firm',      type: 'deal' },
  { stat: 'focus',       threshold: 30, label: 'Deep Analysis',         description: 'Unlock advanced market reports',     type: 'deal' },
  { stat: 'discipline',  threshold: 30, label: 'No-Trade Mastery',      description: 'Streak multiplier activates',        type: 'deal' },
  { stat: 'reputation',  threshold: 50,  label: 'Northern Territories', description: 'Unlock Braga & Coimbra early',       type: 'territory' },
  { stat: 'reputation',  threshold: 100, label: 'Island Access',        description: 'Unlock Madeira & Açores early',      type: 'territory' },
  { stat: 'reputation',  threshold: 150, label: 'Legendary Quests',     description: 'New legendary quests available',     type: 'quest' },
];

// ─── Territory helpers ────────────────────────────────────────────────────────

export interface TerritoryStatus {
  isAccessible: boolean;
  isActive: boolean;
  isControlled: boolean;
  isDominating: boolean;
  tierLabel: string;
  tierColor: string;
}

export const getTerritoryStatus = (
  district: District,
  playerDistrict: PlayerDistrict | undefined,
  playerLevel: number
): TerritoryStatus => {
  const isAccessible = playerLevel >= district.unlock_requirement;
  const isActive = !!playerDistrict && playerDistrict.is_unlocked;
  const territoryLevel = playerDistrict?.territory_level ?? 0;
  const marketShare = playerDistrict?.market_share ?? 0;
  const isControlled = isActive && territoryLevel >= 3;
  const isDominating = isActive && marketShare >= 0.5;

  const tierMap: Record<number, { label: string; color: string }> = {
    0: { label: 'Unexplored', color: 'text-slate-500' },
    1: { label: 'Scouting',   color: 'text-blue-400' },
    2: { label: 'Established',color: 'text-cyan-400' },
    3: { label: 'Dominant',   color: 'text-amber-400' },
    4: { label: 'Authority',  color: 'text-orange-400' },
    5: { label: 'Empire',     color: 'text-red-400' },
  };

  const tier = tierMap[Math.min(territoryLevel, 5)];

  return {
    isAccessible,
    isActive,
    isControlled,
    isDominating,
    tierLabel: isActive ? tier.label : isAccessible ? 'Available' : 'Locked',
    tierColor: isActive ? tier.color : isAccessible ? 'text-slate-300' : 'text-slate-600',
  };
};

export const xpForTerritoryLevel = (level: number): number => {
  const thresholds = [0, 200, 500, 1000, 2000, 4000];
  return thresholds[Math.min(level, 5)];
};

// XP required to reach a given player level
export const xpRequiredForLevel = (level: number): number => {
  if (level <= 1) return 0;
  return Math.floor(1000 * Math.pow(1.15, level - 2));
};

export const SKILL_LABELS: Record<keyof PlayerSkills, string> = {
  negotiation: 'Negotiation',
  networking:  'Networking',
  focus:       'Focus',
  discipline:  'Discipline',
  leadership:  'Leadership',
  reputation:  'Reputation',
};

export const SKILL_COLORS: Record<keyof PlayerSkills, string> = {
  negotiation: '#f59e0b',
  networking:  '#3b82f6',
  focus:       '#10b981',
  discipline:  '#06b6d4',
  leadership:  '#ef4444',
  reputation:  '#a855f7',
};

export const SKILL_ICONS: Record<keyof PlayerSkills, string> = {
  negotiation: '🤝',
  networking:  '🌐',
  focus:       '🎯',
  discipline:  '🛡️',
  leadership:  '👑',
  reputation:  '⭐',
};

// ─── Leads & Matching Engine ──────────────────────────────────────────────────

export type LeadTipo = 'Investidor' | 'Proprietário';
export type LeadUrgency = 'low' | 'medium' | 'high' | 'urgent';
export type LeadSource = 'manual' | 'referral' | 'event' | 'inbound';
export type LeadStatus = 'active' | 'matched' | 'closed' | 'inactive';
export type MatchTier = 'legendary' | 'strong' | 'warm' | 'low' | 'budget_mismatch' | 'incomplete_data';

export interface Lead {
  id: string;
  player_id: string;
  notion_page_id: string | null;
  tipo: LeadTipo;
  name: string;
  company: string | null;
  email: string | null;
  phone: string | null;
  locations: string[];
  asset_types: string[];
  investment_min: number;
  investment_max: number;
  estimated_value: number;
  urgency: LeadUrgency;
  notes: string | null;
  source: LeadSource;
  status: LeadStatus;
  // Extended fields from bidirectional sync
  stars: number;
  rooms: number | null;
  last_contact_at: string | null;
  next_follow_up: string | null;
  status_updated_at: string | null;
  notion_last_synced_at: string | null;
  bolt_last_updated_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface LeadMatch {
  id: string;
  player_id: string;
  investor_lead_id: string;
  owner_lead_id: string;
  match_score: number;
  match_tier: MatchTier;
  match_reasons: string[];
  suggested_action: string;
  opportunity_type: string;
  district_id: string | null;
  xp_awarded: number;
  quest_generated: boolean;
  is_dismissed: boolean;
  is_actioned: boolean;
  created_at: string;
  // Joined
  investor?: Lead;
  owner?: Lead;
}

export const MATCH_TIER_META: Record<MatchTier, {
  label: string; color: string; glow: string; bg: string; badge: string; minScore: number;
}> = {
  legendary:       { label: 'Legendary Match',    color: '#f59e0b', glow: 'rgba(245,158,11,0.4)',  bg: 'rgba(245,158,11,0.08)', badge: 'LEGENDARY',        minScore: 80 },
  strong:          { label: 'Strong Match',        color: '#10b981', glow: 'rgba(16,185,129,0.35)', bg: 'rgba(16,185,129,0.07)', badge: 'STRONG',           minScore: 60 },
  warm:            { label: 'Warm Opportunity',    color: '#3b82f6', glow: 'rgba(59,130,246,0.3)',  bg: 'rgba(59,130,246,0.06)', badge: 'WARM',             minScore: 40 },
  low:             { label: 'Low Compatibility',   color: '#475569', glow: 'rgba(71,85,105,0.2)',   bg: 'rgba(71,85,105,0.04)', badge: 'LOW',              minScore: 1  },
  budget_mismatch: { label: 'Budget Mismatch',     color: '#ef4444', glow: 'rgba(239,68,68,0.25)',  bg: 'rgba(239,68,68,0.05)', badge: 'BUDGET MISMATCH',  minScore: 0  },
  incomplete_data: { label: 'Incomplete Lead Data',color: '#94a3b8', glow: 'rgba(148,163,184,0.2)', bg: 'rgba(148,163,184,0.04)',badge: 'INCOMPLETE DATA', minScore: 0  },
};

export const ASSET_TYPE_OPTIONS = [
  'boutique', 'resort', 'hostel', 'aparthotel', 'pension',
  'heritage', 'rural', 'urban', 'beachfront', 'wellness',
  'luxury', 'budget', 'business',
] as const;

export const LOCATION_OPTIONS = [
  'Lisbon', 'Porto', 'Algarve', 'Cascais', 'Sintra', 'Braga',
  'Coimbra', 'Évora', 'Faro', 'Setúbal', 'Aveiro', 'Madeira',
  'Azores', 'Douro Valley', 'Alentejo', 'Silver Coast',
] as const;

// ─── Energy action costs / gains ──────────────────────────────────────────────

export interface EnergyDelta {
  energy?: number;    // positive = gain, negative = cost
  stress?: number;    // positive = increase (bad), negative = reduce (good)
  morale?: number;    // positive = gain (good), negative = loss (bad)
  focus?: number;     // positive = gain, negative = loss
}

export const ENERGY_ACTIONS = {
  // Consuming actions
  client_call:        { energy: -8,  stress: +5,  morale: 0,   focus: -3  } as EnergyDelta,
  partner_meeting:    { energy: -12, stress: +6,  morale: +4,  focus: -4  } as EnergyDelta,
  site_visit:         { energy: -15, stress: +4,  morale: +6,  focus: -5  } as EnergyDelta,
  // Trading penalty
  trading_action:     { energy: -10, stress: +20, morale: -15, focus: -12 } as EnergyDelta,
  // Restorative actions
  rest:               { energy: +25, stress: -15, morale: +5,  focus: +8  } as EnergyDelta,
  morning_routine:    { energy: +20, stress: -10, morale: +8,  focus: +12 } as EnergyDelta,
  // Deal outcomes
  deal_success:       { energy: +10, stress: -8,  morale: +20, focus: +5  } as EnergyDelta,
  deal_small:         { energy: +5,  stress: -4,  morale: +10, focus: +3  } as EnergyDelta,
  // Quest completions
  quest_complete:     { energy: +6,  stress: -5,  morale: +8,  focus: +4  } as EnergyDelta,
} as const;
